spring:
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://43.139.117.216:3306/simulator
    username: root
    password: wzwzywb
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      password: redis-password
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.unityauth.mapper
