spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simulator
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      password: redis-password
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.unityauth.mapper